site_name: Grupo 03 - Procon
repo_url: https://github.com/Interacao-Humano-Computador/2026.1-Grupo03
repo_name: Interacao-Humano-Computador/2026.1-Grupo03
theme:
  name: material
  logo: equipe/images/procon-logo.webp
  favicon: equipe/images/procon-logo.webp
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para modo Escuro
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo Claro

extra_css:
  - stylesheets/extra.css

plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Início: index.md
  - A Equipe:
      - Equipe: equipe/equipe.md
      - Disponibilidade: equipe/disponibilidade.md
  - Planejamento:
      - Cronograma: planejamento/cronograma.md
      - Reuniões: planejamento/reunioes.md
  - Projeto:
      - Análise de Sites: projeto/analise-sites.md
      - Lista de Verificação: planejamento/verificacao.md
      - Ferramentas: planejamento/ferramentas.md
      - Processo de Design: planejamento/processo-design.md
      - Site Escolhido: planejamento/site-escolhido.md
  - Inspeção:
    - Entrega 01: inspecoes/entrega01.md
